global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nestjs_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3001'] # Assuming NestJS runs on port 3001, adjust if needed
